spring:
 application:
  name: gateway-service
 security:
  oauth2:
   resourceserver:
    jwt:
     issuer-uri: http://localhost:8080/realms/pruebaMicro
 cloud:
  config:
   discovery:
    enable: true
    serviceId: config-service
  gateway:
   default-filters:
    - TokenRelay=
   routes:
    - id: checkout-service
      uri: lb://checkout-service
      predicates:
        - Path=/checkout
      filters:
        - AddRequestHeader=X-Request-from, gateway
    - id: products-service
      uri: lb://products-service
      predicates:
        - Path=/products
server:
 port: 8084


